// generated by https://json2csharp.com/
// Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
using Newtonsoft.Json;

namespace RiotMatchTimeline
{
    public class _1
    {
        public ChampionStats championStats { get; set; }
        public int currentGold { get; set; }
        public DamageStats damageStats { get; set; }
        public int goldPerSecond { get; set; }
        public int jungleMinionsKilled { get; set; }
        public int level { get; set; }
        public int minionsKilled { get; set; }
        public int participantId { get; set; }
        public Position position { get; set; }
        public int timeEnemySpentControlled { get; set; }
        public int totalGold { get; set; }
        public int xp { get; set; }
    }

    public class _10
    {
        public ChampionStats championStats { get; set; }
        public int currentGold { get; set; }
        public DamageStats damageStats { get; set; }
        public int goldPerSecond { get; set; }
        public int jungleMinionsKilled { get; set; }
        public int level { get; set; }
        public int minionsKilled { get; set; }
        public int participantId { get; set; }
        public Position position { get; set; }
        public int timeEnemySpentControlled { get; set; }
        public int totalGold { get; set; }
        public int xp { get; set; }
    }

    public class _2
    {
        public ChampionStats championStats { get; set; }
        public int currentGold { get; set; }
        public DamageStats damageStats { get; set; }
        public int goldPerSecond { get; set; }
        public int jungleMinionsKilled { get; set; }
        public int level { get; set; }
        public int minionsKilled { get; set; }
        public int participantId { get; set; }
        public Position position { get; set; }
        public int timeEnemySpentControlled { get; set; }
        public int totalGold { get; set; }
        public int xp { get; set; }
    }

    public class _3
    {
        public ChampionStats championStats { get; set; }
        public int currentGold { get; set; }
        public DamageStats damageStats { get; set; }
        public int goldPerSecond { get; set; }
        public int jungleMinionsKilled { get; set; }
        public int level { get; set; }
        public int minionsKilled { get; set; }
        public int participantId { get; set; }
        public Position position { get; set; }
        public int timeEnemySpentControlled { get; set; }
        public int totalGold { get; set; }
        public int xp { get; set; }
    }

    public class _4
    {
        public ChampionStats championStats { get; set; }
        public int currentGold { get; set; }
        public DamageStats damageStats { get; set; }
        public int goldPerSecond { get; set; }
        public int jungleMinionsKilled { get; set; }
        public int level { get; set; }
        public int minionsKilled { get; set; }
        public int participantId { get; set; }
        public Position position { get; set; }
        public int timeEnemySpentControlled { get; set; }
        public int totalGold { get; set; }
        public int xp { get; set; }
    }

    public class _5
    {
        public ChampionStats championStats { get; set; }
        public int currentGold { get; set; }
        public DamageStats damageStats { get; set; }
        public int goldPerSecond { get; set; }
        public int jungleMinionsKilled { get; set; }
        public int level { get; set; }
        public int minionsKilled { get; set; }
        public int participantId { get; set; }
        public Position position { get; set; }
        public int timeEnemySpentControlled { get; set; }
        public int totalGold { get; set; }
        public int xp { get; set; }
    }

    public class _6
    {
        public ChampionStats championStats { get; set; }
        public int currentGold { get; set; }
        public DamageStats damageStats { get; set; }
        public int goldPerSecond { get; set; }
        public int jungleMinionsKilled { get; set; }
        public int level { get; set; }
        public int minionsKilled { get; set; }
        public int participantId { get; set; }
        public Position position { get; set; }
        public int timeEnemySpentControlled { get; set; }
        public int totalGold { get; set; }
        public int xp { get; set; }
    }

    public class _7
    {
        public ChampionStats championStats { get; set; }
        public int currentGold { get; set; }
        public DamageStats damageStats { get; set; }
        public int goldPerSecond { get; set; }
        public int jungleMinionsKilled { get; set; }
        public int level { get; set; }
        public int minionsKilled { get; set; }
        public int participantId { get; set; }
        public Position position { get; set; }
        public int timeEnemySpentControlled { get; set; }
        public int totalGold { get; set; }
        public int xp { get; set; }
    }

    public class _8
    {
        public ChampionStats championStats { get; set; }
        public int currentGold { get; set; }
        public DamageStats damageStats { get; set; }
        public int goldPerSecond { get; set; }
        public int jungleMinionsKilled { get; set; }
        public int level { get; set; }
        public int minionsKilled { get; set; }
        public int participantId { get; set; }
        public Position position { get; set; }
        public int timeEnemySpentControlled { get; set; }
        public int totalGold { get; set; }
        public int xp { get; set; }
    }

    public class _9
    {
        public ChampionStats championStats { get; set; }
        public int currentGold { get; set; }
        public DamageStats damageStats { get; set; }
        public int goldPerSecond { get; set; }
        public int jungleMinionsKilled { get; set; }
        public int level { get; set; }
        public int minionsKilled { get; set; }
        public int participantId { get; set; }
        public Position position { get; set; }
        public int timeEnemySpentControlled { get; set; }
        public int totalGold { get; set; }
        public int xp { get; set; }
    }

    public class ChampionStats
    {
        public int abilityHaste { get; set; }
        public int abilityPower { get; set; }
        public int armor { get; set; }
        public int armorPen { get; set; }
        public int armorPenPercent { get; set; }
        public int attackDamage { get; set; }
        public int attackSpeed { get; set; }
        public int bonusArmorPenPercent { get; set; }
        public int bonusMagicPenPercent { get; set; }
        public int ccReduction { get; set; }
        public int cooldownReduction { get; set; }
        public int health { get; set; }
        public int healthMax { get; set; }
        public int healthRegen { get; set; }
        public int lifesteal { get; set; }
        public int magicPen { get; set; }
        public int magicPenPercent { get; set; }
        public int magicResist { get; set; }
        public int movementSpeed { get; set; }
        public int omnivamp { get; set; }
        public int physicalVamp { get; set; }
        public int power { get; set; }
        public int powerMax { get; set; }
        public int powerRegen { get; set; }
        public int spellVamp { get; set; }
    }

    public class DamageStats
    {
        public int magicDamageDone { get; set; }
        public int magicDamageDoneToChampions { get; set; }
        public int magicDamageTaken { get; set; }
        public int physicalDamageDone { get; set; }
        public int physicalDamageDoneToChampions { get; set; }
        public int physicalDamageTaken { get; set; }
        public int totalDamageDone { get; set; }
        public int totalDamageDoneToChampions { get; set; }
        public int totalDamageTaken { get; set; }
        public int trueDamageDone { get; set; }
        public int trueDamageDoneToChampions { get; set; }
        public int trueDamageTaken { get; set; }
    }

    public class Event
    {
        public object realTimestamp { get; set; }
        public int timestamp { get; set; }
        public string type { get; set; }
        public int? itemId { get; set; }
        public int? participantId { get; set; }
        public string levelUpType { get; set; }
        public int? skillSlot { get; set; }
        public int? creatorId { get; set; }
        public string wardType { get; set; }
        public int? level { get; set; }
        public int? afterId { get; set; }
        public int? beforeId { get; set; }
        public int? goldGain { get; set; }
        public int? killerId { get; set; }
        public List<int> assistingParticipantIds { get; set; }
        public int? bounty { get; set; }
        public int? killerTeamId { get; set; }
        public string monsterSubType { get; set; }
        public string monsterType { get; set; }
        public Position position { get; set; }
        public string laneType { get; set; }
        public int? teamId { get; set; }
        public int? killStreakLength { get; set; }
        public int? shutdownBounty { get; set; }
        public List<VictimDamageDealt> victimDamageDealt { get; set; }
        public List<VictimDamageReceived> victimDamageReceived { get; set; }
        public int? victimId { get; set; }
        public string killType { get; set; }
        public string buildingType { get; set; }
        public string towerType { get; set; }
        public int? actualStartTime { get; set; }
        public string name { get; set; }
        public int? multiKillLength { get; set; }
        public long? gameId { get; set; }
        public int? winningTeam { get; set; }
    }

    public class Frame
    {
        public List<Event> events { get; set; }
        public ParticipantFrames participantFrames { get; set; }
        public int timestamp { get; set; }
    }

    public class Info
    {
        public string endOfGameResult { get; set; }
        public int frameInterval { get; set; }
        public List<Frame> frames { get; set; }
        public long gameId { get; set; }
        public List<Participant> participants { get; set; }
    }

    public class Metadata
    {
        public string dataVersion { get; set; }
        public string matchId { get; set; }
        public List<string> participants { get; set; }
    }

    public class Participant
    {
        public int participantId { get; set; }
        public string puuid { get; set; }
    }

    public class ParticipantFrames
    {
        [JsonProperty("1")]
        public _1 _1 { get; set; }

        [JsonProperty("2")]
        public _2 _2 { get; set; }

        [JsonProperty("3")]
        public _3 _3 { get; set; }

        [JsonProperty("4")]
        public _4 _4 { get; set; }

        [JsonProperty("5")]
        public _5 _5 { get; set; }

        [JsonProperty("6")]
        public _6 _6 { get; set; }

        [JsonProperty("7")]
        public _7 _7 { get; set; }

        [JsonProperty("8")]
        public _8 _8 { get; set; }

        [JsonProperty("9")]
        public _9 _9 { get; set; }

        [JsonProperty("10")]
        public _10 _10 { get; set; }
    }

    public class Position
    {
        public int x { get; set; }
        public int y { get; set; }
    }

    public class RiotMatchTimeline
    {
        public Metadata metadata { get; set; }
        public Info info { get; set; }
    }

    public class VictimDamageDealt
    {
        public bool basic { get; set; }
        public int magicDamage { get; set; }
        public string name { get; set; }
        public int participantId { get; set; }
        public int physicalDamage { get; set; }
        public string spellName { get; set; }
        public int spellSlot { get; set; }
        public int trueDamage { get; set; }
        public string type { get; set; }
    }

    public class VictimDamageReceived
    {
        public bool basic { get; set; }
        public int magicDamage { get; set; }
        public string name { get; set; }
        public int participantId { get; set; }
        public int physicalDamage { get; set; }
        public string spellName { get; set; }
        public int spellSlot { get; set; }
        public int trueDamage { get; set; }
        public string type { get; set; }
    }
}